### ISSUE TITLE
Flatpak version not run

### ISSUE THREAD

**Issue by guglovich** [kozec/syncthing-gtk#569]
Gtk-Message: 14:27:48.065: Failed to load module "canberra-gtk-module"
Gtk-Message: 14:27:48.065: Failed to load module "xapp-gtk3-module"
Gtk-Message: 14:27:48.065: Failed to load module "canberra-gtk-module"
Gtk-Message: 14:27:48.065: Failed to load module "xapp-gtk3-module"
W Configuration Failed to load configuration; Creating new one.
W Configuration Reason: (IOError(2, '\xd0\x9d\xd0\xb5\xd1\x82 \xd1\x82\xd0\xb0\xd0\xba\xd0\xbe\xd0\xb3\xd0\xbe \xd1\x84\xd0\xb0\xd0\xb9\xd0\xbb\xd0\xb0 \xd0\xb8\xd0\xbb\xd0\xb8 \xd0\xba\xd0\xb0\xd1\x82\xd0\xb0\xd0\xbb\xd0\xbe\xd0\xb3\xd0\xb0'),)
I StatusIcon    Using backend StatusIconGTK3 (primary)
Traceback (most recent call last):
  File "/app/lib/python2.7/site-packages/syncthing_gtk/app.py", line 242, in do_command_line
    if self.setup_connection():
  File "/app/lib/python2.7/site-packages/syncthing_gtk/app.py", line 385, in setup_connection
    self.daemon = Daemon()
  File "/app/lib/python2.7/site-packages/syncthing_gtk/daemon.py", line 321, in __init__
    self._read_config()
  File "/app/lib/python2.7/site-packages/syncthing_gtk/daemon.py", line 337, in _read_config
    raise InvalidConfigurationException("Failed to read daemon configuration: %s" % e)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 10: ordinal not in range(128)

**Comment by guglovich** [comment]
Launched from the app drawer, but the buttons in the settings do not work. Only the interface settings can be opened.
![Снимок экрана_2020-12-09_15-16-15](https://user-images.githubusercontent.com/54148165/101628848-82f78480-3a31-11eb-95e5-f4d891fba2e9.png)

**Comment by muelli** [comment]
Report this against the flatpak package, please: https://github.com/flathub/me.kozec.syncthingtk/issues/new
