### ISSUE TITLE
Doesn't Launch After Updating

### ISSUE THREAD

**Issue by ProfessorCode212** [kozec/syncthing-gtk#589]
When I try to launch Syncthing-GTK, the following error occurs. It even launched _just before_ I applied the update but it crashed afterwards.

```
~$ flatpak run me.kozec.syncthingtk --version
Traceback (most recent call last):
  File "/app/bin/syncthing-gtk", line 32, in <module>
    from syncthing_gtk.app import App
  File "/app/lib/python2.7/site-packages/syncthing_gtk/app.py", line 19, in <module>
    from syncthing_gtk.notifications import Notifications, HAS_DESKTOP_NOTIFY
  File "/app/lib/python2.7/site-packages/syncthing_gtk/notifications.py", line 21, in <module>
    gi.require_version('Notify', '0.7')
  File "/app/lib/python2.7/site-packages/gi/__init__.py", line 133, in require_version
    (namespace, version))
ValueError: Namespace Notify not available for version 0.7
```

**OS:** Linux Mint 20
**Installation Method:** Flatpak
**Version:** 0.9.4.4

**Comment by licaon-kter** [comment]
@ProfessorCode212 what was the fix? Is it a sekret?

/LE: got it, apply this https://github.com/kozec/syncthing-gtk/commit/11d095a2d864f9f8c95e73dbaf843c7b5dac6c79
